### PR TITLE
Sandbox/Mobile UI

### PR DESCRIPTION
**Pull request by murderteeth**
### Mobile First
Styles and layout for the app's chrome (header, menu, etc) and vault browser were refactored to be mobile first. Note that tailwindcss is a mobile first css utility, so this wasn't too hard and it should be relatively easy for new screens going forward.

### Sandbox
The sandbox went through a (mobile first) design iteration. I think everything worked out pretty well with the exception of drag-and-drop to reorder blocks. While you _can_ drag/drop the blocks to reorder them, the UI isn't so great on Windows and Android (it should be fine on MacOS, haven't tried on iOS). The drag/drop library I used is using the HTML5 drag/drop api under the hood which, for example, has known UI issues on Windows:
https://stackoverflow.com/questions/18841228/draggable-item-faded-and-ugly

We can fix this of course. I chose that particular drag/drop lib because it's really simple to implement. There are others we can try, but I'd like to punt that to a future PR just for drag/drop.

Also note, I ended up refactoring everything that was previously under /buildingBlocks to components under /Sandbox and /AddBlockDialog.

### Vault tile redesign
The previous tile design was busy/cluttered. The new design borrows from a popular contact card design. It's streamlined and presents more intuitive click targets. It also has space for an avatar/icon for each vault. Yearnwatch shows vault icons, for example. I didn't make time to grok how/from where Yearnwatch is getting those icons. But I figure that's an easy PR to make downstream. For now, I just left a circle on each tile showing where an icon might go.

image

### CODE REVIEW

**Comment by flashfish0x** [comment]
Looking good! 

One comment. Looks like the add block doesn't appear when you fill in a text box

image

**Comment by murderteeth** [comment]
> Looking good!
> 
> One comment. Looks like the add block doesn't appear when you fill in a text box
> 
> image

**Comment by flashfish0x** [comment]
The tile layout is cool. I think we will want to put some information in the place of the icon as an image isnt too useful for us. I will have a think of what info to show there. maybe a graph or some other information

**Comment by murderteeth** [comment]
> Looking good!
> 
> One comment. Looks like the add block doesn't appear when you fill in a text box
> 
> image

In this case, the button is disabled because of data validation (it's validating threshold as a number). So this behavior is expected. However, I did notice a race condition during testing that will cause `Add block` to remain disabled even with valid data. It happens very rarely, some kind of race condition I think. Will debug more in the future.

**Pull request merged**
