### PR TITLE
`Loading.js` replaced by `Spinner.js`

### LINKED ISSUE #126: Chore: Replace Loading.js with Spinner.tsx
Replace occurrences of: https://github.com/yearn/dashboard_ui/blob/main/src/components/Loading.js
With: https://github.com/yearn/dashboard_ui/blob/main/src/components/controls/Spinner.tsx
Remove Loading.js from the project.

### PR DESCRIPTION
**Pull request by Rishav1707**
## This PR closes the following issue:
closes #126

### CODE REVIEW

**Review by murderteeth — APPROVED** [review]
nice work, lgtm. please merge =)

**Comment by murderteeth** [comment]
Hey @Rishav1707, merge whenever you're ready

**Comment by Rishav1707** [comment]
> Hey @Rishav1707, merge whenever you're ready

How?

**Comment by murderteeth** [comment]
> > Hey @Rishav1707, merge whenever you're ready
> 
> How?

Oh thought you had access, my bad! nm

**Pull request merged**
